version: '3.4'

services:
  logcorner.edusync.signalr.server:
    image: ${DOCKER_REGISTRY-}/logcorner-edusync-signalr-server
    build:
      context: .
      dockerfile: LogCorner.EduSync.SignalR.Server/Dockerfile
    networks:
      - speech_network

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

#networks:
 # elastic:
 #   driver: bridge
networks:
  speech_network:
    external:
      name: speech_network



